# Copyright 2021 David Garcia
# See LICENSE file for licensing details.

options:
  java-opts:
    description: JAVA_OPT
    type: string
    default: "-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -Dds.lock.timeout.milliseconds=15000"
  enable-gui:
    description: Enable the ONOS gui at port 8181
    type: boolean
    default: True